# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country_get for http method type GET 
# RoostTestHash=3d9e7cb5d1
# 
# 

# ********RoostGPT********
Feature: Validate Get All Countries API

  Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * header Accept = 'application/json'
    * header app-identifier = "<app_identifier>"
    * header customer-secret-key = "<customer_secret_key>"

  Scenario Outline: Verify successful retrieval of countries
    Given path 'country'
    When method GET
    Then status 200
    And match response.status == 'success'
    And match response.message == '#string'
    And match response.data.countries == '#[]'
    And match each response.data.countries[*].id == '#number'
    And match each response.data.countries[*].name == '#? _ == null || typeof _ == "string"'
    And match each response.data.countries[*].code == '#string'
    And match each response.data.countries[*].default_currency == '#string'
    And match each response.data.countries[*].is_active == '#number'
    And match each response.data.countries[*].app_id == '#number'
    And match each response.data.countries[*].customer_id == '#number'
    And match each response.data.countries[*].created_by == '#number'
    And match each response.data.countries[*].updated_by == '#number'
    And match each response.data.countries[*].created_at == '#regex ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$'
    And match each response.data.countries[*].updated_at == '#regex ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$'
    And match each response.data.countries[*].currencies == '#[]'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_get.csv') |
