
// ********RoostGPT********
/*

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country_post for http method type POST 
# RoostTestHash=6873c73aa2
# 
# 

roost_feedback [11/08/2025, 8:46:07 AM]:-\sAdd\smore\scomments\sto\sthe\stest
*/

// ********RoostGPT********

Feature: Tests for Create New Country endpoint

Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate Create New Country API with multiple valid combinations of request payload
    Given path 'country'
    When requestHeaders { Authorization: '#(authToken)', Accept: 'application/json' }
    And request
      """
      {
        "name": "<name>",
        "summary": "<summary>"
      }
      """
    Then status 201
    And match response == { success: true }

    Examples:
      | read('country_post.csv') |
