# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=e702c0f931
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Laureate API Tests

  Background:
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * header Accept = 'application/json'

  Scenario Outline: Get Nobel Prize Laureate by ID - Success Response
    Given path '/2.1/laureate/<laureateID>'
    When method GET
    Then status 200
    And match response.laureate.id == '#number'
    And match response.laureate.laureateIfPerson.knownName.en == '#string'
    And match response.laureate.laureateIfPerson.givenName.en == '#string'
    And match response.laureate.laureateIfPerson.familyName.en == '#string'
    And match response.laureate.laureateIfPerson.fullName.en == '#string'
    And match response.laureate.laureateIfPerson.filename == '#string'
    And match response.laureate.laureateIfPerson.gender == '#string'
    And match response.laureate.laureateIfPerson.birth.date == '#string'
    And match response.laureate.laureateIfPerson.birth.place.city.en == '#string'
    And match each response.laureate.nobelPrizes[*].awardYear == '#number'
    And match response.laureate.wikidata.id == '#string'
    And match each response.laureate.sameAs[*] == '#string'
    And match each response.laureate.links[*].href == '#string'

    Examples:
      | laureateID |
      | [ '1' ]    |
      | [ '456' ]  |

  Scenario: Get Nobel Prize Laureate by Invalid ID - Status 404
    Given path '/2.1/laureate/999999'
    When method GET
    Then status 404
    And match response == """
    {
        "code": "#string",
        "message": "#string"
    }
    """

  Scenario: Get Nobel Prize Laureate by Malformed ID - Status 400
    Given path '/2.1/laureate/abc'
    When method GET
    Then status 400
    And match response == """
    {
        "code": "#string",
        "message": "#string"
    }
    """

  Scenario: Get Nobel Prize Laureate with Unprocessable ID - Status 422
    Given path '/2.1/laureate/0'
    When method GET
    Then status 422
    And match response == """
    {
        "code": "#string",
        "message": "#string"
    }
    """
